export const SIGNUP = 'SIGNUP'
export const ERROR_SIGNUP = 'ERROR_SIGNUP'
export const LOGIN = 'LOGIN'
export const ERROR_LOGIN = 'ERROR_LOGIN'
export const LOGEDIN = 'LOGED_IN'
export const API_END='API_END'
export const LOG_OUT = 'LOG_OUT'