export const ALL_RECIPES = 'ALL_RECIPES'
export const UPDATE_RECIPE = 'UPDATE_RECIPE'
export const DELETE_RECIPE = 'DELETE_RECIPE'
export const ADD_RECIPE = 'ADD_RECIPE'
export const USER_RECIPES = 'USER_RECIPES'
export const RECIPE_DETAILS = 'RECIPE_DETAILS'
export const API_END = 'API_END'
